version: '2'
services:
    ecapiui-app:
        image: ecapiui
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://ecapiui-mysql:3306/ecapiui?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ecapiui-mysql:
        extends:
            file: mysql.yml
            service: ecapiui-mysql
